apiVersion: v1
kind: PersistentVolume
metadata:
  name: testpv
spec:
  storageClassName: "test"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/orders
