apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: order-pvc
spec:
  storageClassName: "test"
  volumeName: testpv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
